// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSavJRFRKRlnG93srQNoo1fzX6BtGCGAA',
    appId: '1:511639600065:web:fd9e22ad785a9f6b160d40',
    messagingSenderId: '511639600065',
    projectId: 'citywealthlive',
    authDomain: 'citywealthlive.firebaseapp.com',
    storageBucket: 'citywealthlive.appspot.com',
    measurementId: 'G-NTCJ8773MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQqYKyJ6zUq2edZNb3j1bYj3vqYeBHC0k',
    appId: '1:511639600065:android:12ab02c8a68c362d160d40',
    messagingSenderId: '511639600065',
    projectId: 'citywealthlive',
    storageBucket: 'citywealthlive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHm9XTWDu6Lqn8dZ_l1LepqZaE55BgnWY',
    appId: '1:511639600065:ios:7ef8632955c0ffe5160d40',
    messagingSenderId: '511639600065',
    projectId: 'citywealthlive',
    storageBucket: 'citywealthlive.appspot.com',
    iosClientId: '511639600065-pdj2rmd37j9ia4lg6m072sbogf4kubim.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityWealthLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHm9XTWDu6Lqn8dZ_l1LepqZaE55BgnWY',
    appId: '1:511639600065:ios:7ef8632955c0ffe5160d40',
    messagingSenderId: '511639600065',
    projectId: 'citywealthlive',
    storageBucket: 'citywealthlive.appspot.com',
    iosClientId: '511639600065-pdj2rmd37j9ia4lg6m072sbogf4kubim.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityWealthLive',
  );
}
